# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Temp_prj\Python_prj\DQ注数生成工具-20190411\gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(768, 522)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 221, 306))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.spinBox_1 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_1.setMaximum(65535)
        self.spinBox_1.setProperty("value", 5776)
        self.spinBox_1.setDisplayIntegerBase(16)
        self.spinBox_1.setObjectName("spinBox_1")
        self.horizontalLayout_8.addWidget(self.spinBox_1)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.spinBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_2.setMaximum(65535)
        self.spinBox_2.setProperty("value", 49152)
        self.spinBox_2.setDisplayIntegerBase(16)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_9.addWidget(self.spinBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_3.setWrapping(False)
        self.spinBox_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_3.setProperty("showGroupSeparator", False)
        self.spinBox_3.setSuffix("")
        self.spinBox_3.setPrefix("")
        self.spinBox_3.setMaximum(65535)
        self.spinBox_3.setProperty("value", 13)
        self.spinBox_3.setDisplayIntegerBase(16)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_10.addWidget(self.spinBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_4.setMaximum(65535)
        self.spinBox_4.setProperty("value", 10)
        self.spinBox_4.setDisplayIntegerBase(16)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout.addWidget(self.spinBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_5 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_5.setMaximum(65535)
        self.spinBox_5.setProperty("value", 3840)
        self.spinBox_5.setDisplayIntegerBase(16)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_2.addWidget(self.spinBox_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_6 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_6.setMaximum(65535)
        self.spinBox_6.setProperty("value", 88)
        self.spinBox_6.setDisplayIntegerBase(16)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_3.addWidget(self.spinBox_6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spinBox_7 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_7.setMaximum(65535)
        self.spinBox_7.setProperty("value", 60395)
        self.spinBox_7.setDisplayIntegerBase(16)
        self.spinBox_7.setObjectName("spinBox_7")
        self.horizontalLayout_4.addWidget(self.spinBox_7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.spinBox_8 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_8.setMaximum(65535)
        self.spinBox_8.setProperty("value", 60395)
        self.spinBox_8.setDisplayIntegerBase(16)
        self.spinBox_8.setObjectName("spinBox_8")
        self.horizontalLayout_5.addWidget(self.spinBox_8)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.spinBox_9 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_9.setMaximum(65535)
        self.spinBox_9.setProperty("value", 256)
        self.spinBox_9.setDisplayIntegerBase(16)
        self.spinBox_9.setObjectName("spinBox_9")
        self.horizontalLayout_6.addWidget(self.spinBox_9)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.spinBox_10 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_10.setSpecialValueText("")
        self.spinBox_10.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.spinBox_10.setKeyboardTracking(True)
        self.spinBox_10.setMaximum(65535)
        self.spinBox_10.setProperty("value", 0)
        self.spinBox_10.setDisplayIntegerBase(16)
        self.spinBox_10.setObjectName("spinBox_10")
        self.horizontalLayout_7.addWidget(self.spinBox_10)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(240, 20, 521, 151))
        self.groupBox.setObjectName("groupBox")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 70, 60, 16))
        self.label_11.setObjectName("label_11")
        self.pushButton_xor = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_xor.setGeometry(QtCore.QRect(320, 120, 75, 23))
        self.pushButton_xor.setObjectName("pushButton_xor")
        self.lineEdit_cmd_filename = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_cmd_filename.setGeometry(QtCore.QRect(10, 90, 481, 20))
        self.lineEdit_cmd_filename.setClearButtonEnabled(False)
        self.lineEdit_cmd_filename.setObjectName("lineEdit_cmd_filename")
        self.pushButton_cmd_fout = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_cmd_fout.setGeometry(QtCore.QRect(410, 120, 75, 23))
        self.pushButton_cmd_fout.setObjectName("pushButton_cmd_fout")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 261, 21))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.radioButton_1 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_1.setChecked(True)
        self.radioButton_1.setObjectName("radioButton_1")
        self.horizontalLayout_11.addWidget(self.radioButton_1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_11.addWidget(self.radioButton_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 50, 261, 21))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.radioButton_dpc_cmdfmt = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_dpc_cmdfmt.setChecked(True)
        self.radioButton_dpc_cmdfmt.setObjectName("radioButton_dpc_cmdfmt")
        self.horizontalLayout_14.addWidget(self.radioButton_dpc_cmdfmt)
        self.radioButton_dpc_yzfmt = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_dpc_yzfmt.setObjectName("radioButton_dpc_yzfmt")
        self.horizontalLayout_14.addWidget(self.radioButton_dpc_yzfmt)
        self.textBrowser_log = QtWidgets.QTextBrowser(Form)
        self.textBrowser_log.setGeometry(QtCore.QRect(240, 180, 521, 141))
        self.textBrowser_log.setObjectName("textBrowser_log")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 330, 751, 191))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.pushButton_odu_gain_update = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_odu_gain_update.setGeometry(QtCore.QRect(50, 80, 75, 23))
        self.pushButton_odu_gain_update.setObjectName("pushButton_odu_gain_update")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_1)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 20, 156, 55))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.doubleSpinBox_odu_gain = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_odu_gain.setMinimum(1.0)
        self.doubleSpinBox_odu_gain.setMaximum(5.8)
        self.doubleSpinBox_odu_gain.setSingleStep(0.1)
        self.doubleSpinBox_odu_gain.setObjectName("doubleSpinBox_odu_gain")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_odu_gain)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.spinBox_odu_gain_hex = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spinBox_odu_gain_hex.setEnabled(True)
        self.spinBox_odu_gain_hex.setReadOnly(True)
        self.spinBox_odu_gain_hex.setDisplayIntegerBase(16)
        self.spinBox_odu_gain_hex.setObjectName("spinBox_odu_gain_hex")
        self.horizontalLayout_13.addWidget(self.spinBox_odu_gain_hex)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_1)
        self.layoutWidget_2.setGeometry(QtCore.QRect(177, 20, 210, 55))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_15.addWidget(self.label_14)
        self.doubleSpinBox_odu_time = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBox_odu_time.setDecimals(1)
        self.doubleSpinBox_odu_time.setMinimum(5.0)
        self.doubleSpinBox_odu_time.setMaximum(80.0)
        self.doubleSpinBox_odu_time.setSingleStep(0.5)
        self.doubleSpinBox_odu_time.setProperty("value", 5.0)
        self.doubleSpinBox_odu_time.setObjectName("doubleSpinBox_odu_time")
        self.horizontalLayout_15.addWidget(self.doubleSpinBox_odu_time)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.spinBox_odu_time_hex = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_odu_time_hex.setEnabled(True)
        self.spinBox_odu_time_hex.setReadOnly(True)
        self.spinBox_odu_time_hex.setMaximum(200)
        self.spinBox_odu_time_hex.setProperty("value", 10)
        self.spinBox_odu_time_hex.setDisplayIntegerBase(16)
        self.spinBox_odu_time_hex.setObjectName("spinBox_odu_time_hex")
        self.horizontalLayout_16.addWidget(self.spinBox_odu_time_hex)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.pushButton_odu_time_update_1 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_odu_time_update_1.setGeometry(QtCore.QRect(400, 20, 141, 23))
        self.pushButton_odu_time_update_1.setObjectName("pushButton_odu_time_update_1")
        self.pushButton_odu_time_update_2 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_odu_time_update_2.setGeometry(QtCore.QRect(400, 50, 141, 23))
        self.pushButton_odu_time_update_2.setObjectName("pushButton_odu_time_update_2")
        self.pushButton_odu_time_update_3 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_odu_time_update_3.setGeometry(QtCore.QRect(400, 80, 141, 23))
        self.pushButton_odu_time_update_3.setObjectName("pushButton_odu_time_update_3")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_djmode = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_djmode.setGeometry(QtCore.QRect(50, 130, 111, 23))
        self.pushButton_djmode.setObjectName("pushButton_djmode")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(230, 40, 192, 23))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_22.addWidget(self.label_21)
        self.spinBox_dj_work_rpm = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_dj_work_rpm.setEnabled(True)
        self.spinBox_dj_work_rpm.setReadOnly(False)
        self.spinBox_dj_work_rpm.setMinimum(1)
        self.spinBox_dj_work_rpm.setMaximum(65535)
        self.spinBox_dj_work_rpm.setProperty("value", 6346)
        self.spinBox_dj_work_rpm.setDisplayIntegerBase(10)
        self.spinBox_dj_work_rpm.setObjectName("spinBox_dj_work_rpm")
        self.horizontalLayout_22.addWidget(self.spinBox_dj_work_rpm)
        self.pushButton_djrpm = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_djrpm.setGeometry(QtCore.QRect(270, 70, 121, 23))
        self.pushButton_djrpm.setObjectName("pushButton_djrpm")
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(230, 100, 192, 23))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_23.addWidget(self.label_22)
        self.spinBox_dj_relay = QtWidgets.QSpinBox(self.layoutWidget_4)
        self.spinBox_dj_relay.setEnabled(True)
        self.spinBox_dj_relay.setReadOnly(False)
        self.spinBox_dj_relay.setMinimum(1)
        self.spinBox_dj_relay.setMaximum(65535)
        self.spinBox_dj_relay.setProperty("value", 200)
        self.spinBox_dj_relay.setDisplayIntegerBase(10)
        self.spinBox_dj_relay.setObjectName("spinBox_dj_relay")
        self.horizontalLayout_23.addWidget(self.spinBox_dj_relay)
        self.pushButton_djrelay = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_djrelay.setGeometry(QtCore.QRect(270, 130, 111, 23))
        self.pushButton_djrelay.setObjectName("pushButton_djrelay")
        self.layoutWidget_5 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(450, 10, 271, 23))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_24.addWidget(self.label_23)
        self.spinBox_dj_loop_pos = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.spinBox_dj_loop_pos.setEnabled(True)
        self.spinBox_dj_loop_pos.setReadOnly(False)
        self.spinBox_dj_loop_pos.setMinimum(1)
        self.spinBox_dj_loop_pos.setMaximum(65535)
        self.spinBox_dj_loop_pos.setProperty("value", 200)
        self.spinBox_dj_loop_pos.setDisplayIntegerBase(10)
        self.spinBox_dj_loop_pos.setObjectName("spinBox_dj_loop_pos")
        self.horizontalLayout_24.addWidget(self.spinBox_dj_loop_pos)
        self.layoutWidget_6 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_6.setGeometry(QtCore.QRect(450, 40, 271, 23))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_25.addWidget(self.label_24)
        self.spinBox_dj_frame_pos = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.spinBox_dj_frame_pos.setEnabled(True)
        self.spinBox_dj_frame_pos.setReadOnly(False)
        self.spinBox_dj_frame_pos.setMinimum(1)
        self.spinBox_dj_frame_pos.setMaximum(65535)
        self.spinBox_dj_frame_pos.setProperty("value", 200)
        self.spinBox_dj_frame_pos.setDisplayIntegerBase(10)
        self.spinBox_dj_frame_pos.setObjectName("spinBox_dj_frame_pos")
        self.horizontalLayout_25.addWidget(self.spinBox_dj_frame_pos)
        self.layoutWidget_7 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_7.setGeometry(QtCore.QRect(450, 70, 271, 23))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_26.addWidget(self.label_25)
        self.spinBox_dj_loop_width = QtWidgets.QSpinBox(self.layoutWidget_7)
        self.spinBox_dj_loop_width.setEnabled(True)
        self.spinBox_dj_loop_width.setReadOnly(False)
        self.spinBox_dj_loop_width.setMinimum(1)
        self.spinBox_dj_loop_width.setMaximum(255)
        self.spinBox_dj_loop_width.setProperty("value", 200)
        self.spinBox_dj_loop_width.setDisplayIntegerBase(10)
        self.spinBox_dj_loop_width.setObjectName("spinBox_dj_loop_width")
        self.horizontalLayout_26.addWidget(self.spinBox_dj_loop_width)
        self.pushButton_djpos = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_djpos.setGeometry(QtCore.QRect(510, 100, 141, 23))
        self.pushButton_djpos.setObjectName("pushButton_djpos")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 191, 23))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        self.comboBox_djmode = QtWidgets.QComboBox(self.layoutWidget3)
        self.comboBox_djmode.setObjectName("comboBox_djmode")
        self.comboBox_djmode.addItem("")
        self.comboBox_djmode.addItem("")
        self.comboBox_djmode.addItem("")
        self.horizontalLayout_17.addWidget(self.comboBox_djmode)
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 40, 191, 23))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_18.addWidget(self.label_17)
        self.comboBox_djpulse = QtWidgets.QComboBox(self.layoutWidget4)
        self.comboBox_djpulse.setObjectName("comboBox_djpulse")
        self.comboBox_djpulse.addItem("")
        self.comboBox_djpulse.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox_djpulse)
        self.layoutWidget5 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 70, 191, 23))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_19.addWidget(self.label_18)
        self.comboBox_djpower = QtWidgets.QComboBox(self.layoutWidget5)
        self.comboBox_djpower.setObjectName("comboBox_djpower")
        self.comboBox_djpower.addItem("")
        self.comboBox_djpower.addItem("")
        self.horizontalLayout_19.addWidget(self.comboBox_djpower)
        self.layoutWidget6 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 100, 191, 23))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_20.addWidget(self.label_19)
        self.comboBox_djfreq = QtWidgets.QComboBox(self.layoutWidget6)
        self.comboBox_djfreq.setObjectName("comboBox_djfreq")
        self.comboBox_djfreq.addItem("")
        self.comboBox_djfreq.addItem("")
        self.horizontalLayout_20.addWidget(self.comboBox_djfreq)
        self.layoutWidget7 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget7.setGeometry(QtCore.QRect(230, 10, 192, 23))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_21.addWidget(self.label_20)
        self.spinBox_dj_start_rpm = QtWidgets.QSpinBox(self.layoutWidget7)
        self.spinBox_dj_start_rpm.setEnabled(True)
        self.spinBox_dj_start_rpm.setReadOnly(False)
        self.spinBox_dj_start_rpm.setMinimum(1)
        self.spinBox_dj_start_rpm.setMaximum(65535)
        self.spinBox_dj_start_rpm.setProperty("value", 6346)
        self.spinBox_dj_start_rpm.setDisplayIntegerBase(10)
        self.spinBox_dj_start_rpm.setObjectName("spinBox_dj_start_rpm")
        self.horizontalLayout_21.addWidget(self.spinBox_dj_start_rpm)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_wk_t2dn = QtWidgets.QPushButton(self.tab)
        self.pushButton_wk_t2dn.setGeometry(QtCore.QRect(250, 80, 101, 23))
        self.pushButton_wk_t2dn.setObjectName("pushButton_wk_t2dn")
        self.pushButton_wk_dn2t = QtWidgets.QPushButton(self.tab)
        self.pushButton_wk_dn2t.setGeometry(QtCore.QRect(250, 120, 101, 23))
        self.pushButton_wk_dn2t.setObjectName("pushButton_wk_dn2t")
        self.layoutWidget8 = QtWidgets.QWidget(self.tab)
        self.layoutWidget8.setGeometry(QtCore.QRect(30, 10, 223, 23))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_27.addWidget(self.label_28)
        self.spinBox_wk_res_up = QtWidgets.QSpinBox(self.layoutWidget8)
        self.spinBox_wk_res_up.setMaximum(9999999)
        self.spinBox_wk_res_up.setProperty("value", 10000)
        self.spinBox_wk_res_up.setObjectName("spinBox_wk_res_up")
        self.horizontalLayout_27.addWidget(self.spinBox_wk_res_up)
        self.layoutWidget9 = QtWidgets.QWidget(self.tab)
        self.layoutWidget9.setGeometry(QtCore.QRect(30, 70, 181, 23))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_28.addWidget(self.label_29)
        self.spinBox_wk_dnmax = QtWidgets.QSpinBox(self.layoutWidget9)
        self.spinBox_wk_dnmax.setMaximum(65535)
        self.spinBox_wk_dnmax.setProperty("value", 4095)
        self.spinBox_wk_dnmax.setObjectName("spinBox_wk_dnmax")
        self.horizontalLayout_28.addWidget(self.spinBox_wk_dnmax)
        self.layoutWidget10 = QtWidgets.QWidget(self.tab)
        self.layoutWidget10.setGeometry(QtCore.QRect(30, 40, 221, 21))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.radioButton_MF501 = QtWidgets.QRadioButton(self.layoutWidget10)
        self.radioButton_MF501.setChecked(True)
        self.radioButton_MF501.setObjectName("radioButton_MF501")
        self.horizontalLayout_29.addWidget(self.radioButton_MF501)
        self.radioButton_MF61 = QtWidgets.QRadioButton(self.layoutWidget10)
        self.radioButton_MF61.setObjectName("radioButton_MF61")
        self.horizontalLayout_29.addWidget(self.radioButton_MF61)
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget10)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_29.addWidget(self.radioButton)
        self.layoutWidget11 = QtWidgets.QWidget(self.tab)
        self.layoutWidget11.setGeometry(QtCore.QRect(30, 100, 181, 23))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.layoutWidget11)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_30.addWidget(self.label_26)
        self.doubleSpinBox_temperautre_t = QtWidgets.QDoubleSpinBox(self.layoutWidget11)
        self.doubleSpinBox_temperautre_t.setMinimum(-999.0)
        self.doubleSpinBox_temperautre_t.setMaximum(999.0)
        self.doubleSpinBox_temperautre_t.setObjectName("doubleSpinBox_temperautre_t")
        self.horizontalLayout_30.addWidget(self.doubleSpinBox_temperautre_t)
        self.layoutWidget12 = QtWidgets.QWidget(self.tab)
        self.layoutWidget12.setGeometry(QtCore.QRect(30, 130, 181, 23))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.layoutWidget12)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_31.addWidget(self.label_27)
        self.spinBox_temperautre_dn = QtWidgets.QSpinBox(self.layoutWidget12)
        self.spinBox_temperautre_dn.setMaximum(65535)
        self.spinBox_temperautre_dn.setDisplayIntegerBase(16)
        self.spinBox_temperautre_dn.setObjectName("spinBox_temperautre_dn")
        self.horizontalLayout_31.addWidget(self.spinBox_temperautre_dn)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(370, 10, 161, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_10 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_10.setGeometry(QtCore.QRect(10, 60, 143, 23))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_38.addWidget(self.label_36)
        self.doubleSpinBox_rtb = QtWidgets.QDoubleSpinBox(self.layoutWidget_10)
        self.doubleSpinBox_rtb.setDecimals(3)
        self.doubleSpinBox_rtb.setMinimum(-999999.0)
        self.doubleSpinBox_rtb.setMaximum(999999.0)
        self.doubleSpinBox_rtb.setProperty("value", 4622.53)
        self.doubleSpinBox_rtb.setObjectName("doubleSpinBox_rtb")
        self.horizontalLayout_38.addWidget(self.doubleSpinBox_rtb)
        self.layoutWidget_11 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_11.setGeometry(QtCore.QRect(10, 90, 143, 23))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_39.addWidget(self.label_37)
        self.doubleSpinBox_rtc = QtWidgets.QDoubleSpinBox(self.layoutWidget_11)
        self.doubleSpinBox_rtc.setDecimals(3)
        self.doubleSpinBox_rtc.setMinimum(-999999.0)
        self.doubleSpinBox_rtc.setMaximum(999999.0)
        self.doubleSpinBox_rtc.setProperty("value", -86421.72)
        self.doubleSpinBox_rtc.setObjectName("doubleSpinBox_rtc")
        self.horizontalLayout_39.addWidget(self.doubleSpinBox_rtc)
        self.layoutWidget13 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget13.setGeometry(QtCore.QRect(10, 30, 143, 23))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.layoutWidget13)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_37.addWidget(self.label_35)
        self.doubleSpinBox_rta = QtWidgets.QDoubleSpinBox(self.layoutWidget13)
        self.doubleSpinBox_rta.setDecimals(3)
        self.doubleSpinBox_rta.setMinimum(-999999.0)
        self.doubleSpinBox_rta.setMaximum(999999.0)
        self.doubleSpinBox_rta.setProperty("value", -6.01)
        self.doubleSpinBox_rta.setObjectName("doubleSpinBox_rta")
        self.horizontalLayout_37.addWidget(self.doubleSpinBox_rta)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget_8 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_8.setGeometry(QtCore.QRect(20, 20, 191, 23))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_32.addWidget(self.label_30)
        self.comboBox_dpcmode_1 = QtWidgets.QComboBox(self.layoutWidget_8)
        self.comboBox_dpcmode_1.setObjectName("comboBox_dpcmode_1")
        self.comboBox_dpcmode_1.addItem("")
        self.comboBox_dpcmode_1.addItem("")
        self.comboBox_dpcmode_1.addItem("")
        self.horizontalLayout_32.addWidget(self.comboBox_dpcmode_1)
        self.layoutWidget_9 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_9.setGeometry(QtCore.QRect(20, 50, 191, 23))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_33.addWidget(self.label_31)
        self.comboBox_dpcmode_2 = QtWidgets.QComboBox(self.layoutWidget_9)
        self.comboBox_dpcmode_2.setObjectName("comboBox_dpcmode_2")
        self.comboBox_dpcmode_2.addItem("")
        self.comboBox_dpcmode_2.addItem("")
        self.comboBox_dpcmode_2.addItem("")
        self.comboBox_dpcmode_2.addItem("")
        self.horizontalLayout_33.addWidget(self.comboBox_dpcmode_2)
        self.pushButton_dpcmode = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_dpcmode.setGeometry(QtCore.QRect(230, 50, 121, 23))
        self.pushButton_dpcmode.setObjectName("pushButton_dpcmode")
        self.pushButton_orbit = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_orbit.setGeometry(QtCore.QRect(230, 100, 121, 23))
        self.pushButton_orbit.setObjectName("pushButton_orbit")
        self.pushButton_orbit_time = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_orbit_time.setGeometry(QtCore.QRect(470, 100, 121, 23))
        self.pushButton_orbit_time.setObjectName("pushButton_orbit_time")
        self.layoutWidget14 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget14.setGeometry(QtCore.QRect(20, 100, 192, 23))
        self.layoutWidget14.setObjectName("layoutWidget14")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.layoutWidget14)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget14)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_34.addWidget(self.label_32)
        self.spinBox_orbit = QtWidgets.QSpinBox(self.layoutWidget14)
        self.spinBox_orbit.setMaximum(65535)
        self.spinBox_orbit.setProperty("value", 2)
        self.spinBox_orbit.setObjectName("spinBox_orbit")
        self.horizontalLayout_34.addWidget(self.spinBox_orbit)
        self.layoutWidget15 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget15.setGeometry(QtCore.QRect(430, 30, 201, 23))
        self.layoutWidget15.setObjectName("layoutWidget15")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.layoutWidget15)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget15)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_35.addWidget(self.label_33)
        self.doubleSpinBox_orbittime = QtWidgets.QDoubleSpinBox(self.layoutWidget15)
        self.doubleSpinBox_orbittime.setMaximum(999.0)
        self.doubleSpinBox_orbittime.setSingleStep(1.0)
        self.doubleSpinBox_orbittime.setProperty("value", 98.81)
        self.doubleSpinBox_orbittime.setObjectName("doubleSpinBox_orbittime")
        self.horizontalLayout_35.addWidget(self.doubleSpinBox_orbittime)
        self.layoutWidget16 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget16.setGeometry(QtCore.QRect(430, 60, 201, 23))
        self.layoutWidget16.setObjectName("layoutWidget16")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.layoutWidget16)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget16)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_36.addWidget(self.label_34)
        self.spinBox_orbittime_dn = QtWidgets.QSpinBox(self.layoutWidget16)
        self.spinBox_orbittime_dn.setMaximum(999999999)
        self.spinBox_orbittime_dn.setProperty("value", 120000000)
        self.spinBox_orbittime_dn.setDisplayIntegerBase(16)
        self.spinBox_orbittime_dn.setObjectName("spinBox_orbittime_dn")
        self.horizontalLayout_36.addWidget(self.spinBox_orbittime_dn)
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(3)
        self.pushButton_xor.clicked.connect(Form.on_btn_xor_clicked)
        self.pushButton_cmd_fout.clicked.connect(Form.on_btn_cmd_fout_clicked)
        self.pushButton_odu_gain_update.clicked.connect(Form.on_btn_odu_gain_update)
        self.radioButton_dpc_cmdfmt.clicked.connect(Form.on_radio_dpc_cmdfmt)
        self.radioButton_dpc_yzfmt.clicked.connect(Form.on_radio_dpc_yzfmt)
        self.pushButton_odu_time_update_1.clicked.connect(Form.on_btn_odu_time_update_1)
        self.pushButton_odu_time_update_2.clicked.connect(Form.on_btn_odu_time_update_2)
        self.pushButton_odu_time_update_3.clicked.connect(Form.on_btn_odu_time_update_3)
        self.pushButton_djmode.clicked.connect(Form.on_btn_djmode_clicked)
        self.pushButton_djrpm.clicked.connect(Form.on_btn_djrpm_clicked)
        self.pushButton_djrelay.clicked.connect(Form.on_btn_djrelay_clicked)
        self.pushButton_djpos.clicked.connect(Form.on_btn_djpos_clicked)
        self.pushButton_wk_t2dn.clicked.connect(Form.on_btn_wk_t2dn_clicked)
        self.pushButton_wk_dn2t.clicked.connect(Form.on_btn_wk_dn2t_clicked)
        self.pushButton_dpcmode.clicked.connect(Form.on_btn_dpcmode_clicked)
        self.pushButton_orbit.clicked.connect(Form.on_btn_orbit_clicked)
        self.pushButton_orbit_time.clicked.connect(Form.on_btn_orbit_time_clicked)
        self.radioButton_MF501.clicked.connect(Form.on_radio_sel_mf501)
        self.radioButton_MF61.clicked.connect(Form.on_radio_sel_mf61)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.spinBox_1, self.spinBox_2)
        Form.setTabOrder(self.spinBox_2, self.spinBox_3)
        Form.setTabOrder(self.spinBox_3, self.spinBox_4)
        Form.setTabOrder(self.spinBox_4, self.spinBox_5)
        Form.setTabOrder(self.spinBox_5, self.spinBox_6)
        Form.setTabOrder(self.spinBox_6, self.spinBox_7)
        Form.setTabOrder(self.spinBox_7, self.spinBox_8)
        Form.setTabOrder(self.spinBox_8, self.spinBox_9)
        Form.setTabOrder(self.spinBox_9, self.spinBox_10)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DQ注数生成软件"))
        self.groupBox_2.setTitle(_translate("Form", "数据注入或延时注数格式"))
        self.label_8.setText(_translate("Form", "主导头1 "))
        self.label_9.setText(_translate("Form", "主导头2 "))
        self.label_10.setText(_translate("Form", "主导头3 "))
        self.label.setText(_translate("Form", "功能识别 "))
        self.label_2.setText(_translate("Form", "应用数据1"))
        self.label_3.setText(_translate("Form", "应用数据2"))
        self.label_4.setText(_translate("Form", "应用数据3"))
        self.label_5.setText(_translate("Form", "应用数据4"))
        self.label_6.setText(_translate("Form", "应用数据5"))
        self.label_7.setText(_translate("Form", "校 验 和"))
        self.groupBox.setTitle(_translate("Form", "文件输出"))
        self.label_11.setText(_translate("Form", "输出文件名"))
        self.pushButton_xor.setText(_translate("Form", "求累加和"))
        self.lineEdit_cmd_filename.setText(_translate("Form", "DPC光机头部时间设置1-20ms"))
        self.lineEdit_cmd_filename.setPlaceholderText(_translate("Form", "光机头部积分时间设置"))
        self.pushButton_cmd_fout.setText(_translate("Form", "文件输出"))
        self.radioButton_1.setText(_translate("Form", "卫星格式"))
        self.radioButton_2.setText(_translate("Form", "地检格式"))
        self.radioButton_dpc_cmdfmt.setText(_translate("Form", "DPC数据注入"))
        self.radioButton_dpc_yzfmt.setText(_translate("Form", "DPC延时注数"))
        self.pushButton_odu_gain_update.setText(_translate("Form", "增益更新"))
        self.label_12.setText(_translate("Form", "增益-物理量"))
        self.label_13.setText(_translate("Form", "增益-源码"))
        self.label_14.setText(_translate("Form", "积分时间-物理量/ms"))
        self.label_15.setText(_translate("Form", "积分时间-源码"))
        self.pushButton_odu_time_update_1.setText(_translate("Form", "积分时间1批量更新"))
        self.pushButton_odu_time_update_2.setText(_translate("Form", "积分时间2批量更新"))
        self.pushButton_odu_time_update_3.setText(_translate("Form", "积分时间3批量更新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Form", "光机头部注数"))
        self.pushButton_djmode.setText(_translate("Form", "电机模式更新"))
        self.label_21.setText(_translate("Form", "正常转速/十进制"))
        self.pushButton_djrpm.setText(_translate("Form", "电机转速更新"))
        self.label_22.setText(_translate("Form", "延时时间/十进制"))
        self.pushButton_djrelay.setText(_translate("Form", "电机延时更新"))
        self.label_23.setText(_translate("Form", "圈同步脉冲发送位置/十进制"))
        self.label_24.setText(_translate("Form", "帧同步脉冲发送位置/十进制"))
        self.label_25.setText(_translate("Form", "圈同步脉冲发送宽度/十进制"))
        self.pushButton_djpos.setText(_translate("Form", "电机脉冲位置更新"))
        self.label_16.setText(_translate("Form", "工作模式"))
        self.comboBox_djmode.setItemText(0, _translate("Form", "常规转动"))
        self.comboBox_djmode.setItemText(1, _translate("Form", "同步转动"))
        self.comboBox_djmode.setItemText(2, _translate("Form", "反向转动"))
        self.label_17.setText(_translate("Form", "脉冲发送模式"))
        self.comboBox_djpulse.setItemText(0, _translate("Form", "每圈发送"))
        self.comboBox_djpulse.setItemText(1, _translate("Form", "隔圈发送"))
        self.label_18.setText(_translate("Form", "功率驱动模式"))
        self.comboBox_djpower.setItemText(0, _translate("Form", "全功率"))
        self.comboBox_djpower.setItemText(1, _translate("Form", "80%功率"))
        self.label_19.setText(_translate("Form", "斩波频率"))
        self.comboBox_djfreq.setItemText(0, _translate("Form", "20kHz"))
        self.comboBox_djfreq.setItemText(1, _translate("Form", "40kHz"))
        self.label_20.setText(_translate("Form", "启动转速/十进制"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "电机注数"))
        self.pushButton_wk_t2dn.setText(_translate("Form", "温度转源码"))
        self.pushButton_wk_dn2t.setText(_translate("Form", "源码转温度"))
        self.label_28.setText(_translate("Form", "热敏上拉电阻值/欧"))
        self.label_29.setText(_translate("Form", "ADC量程值"))
        self.radioButton_MF501.setText(_translate("Form", "MF501"))
        self.radioButton_MF61.setText(_translate("Form", "MF61"))
        self.radioButton.setText(_translate("Form", "其他"))
        self.label_26.setText(_translate("Form", "温度值-摄氏度"))
        self.label_27.setText(_translate("Form", "温度值十六进制"))
        self.groupBox_3.setTitle(_translate("Form", "热敏电阻系数"))
        self.label_36.setText(_translate("Form", "b:"))
        self.label_37.setText(_translate("Form", "c:"))
        self.label_35.setText(_translate("Form", "a:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "温控注数"))
        self.label_30.setText(_translate("Form", "DPC工作模式"))
        self.comboBox_dpcmode_1.setItemText(0, _translate("Form", "在轨存储"))
        self.comboBox_dpcmode_1.setItemText(1, _translate("Form", "待机模式"))
        self.comboBox_dpcmode_1.setItemText(2, _translate("Form", "观测模式"))
        self.label_31.setText(_translate("Form", "DPC观测状态"))
        self.comboBox_dpcmode_2.setItemText(0, _translate("Form", "独立观测"))
        self.comboBox_dpcmode_2.setItemText(1, _translate("Form", "协同观测"))
        self.comboBox_dpcmode_2.setItemText(2, _translate("Form", "测试观测"))
        self.comboBox_dpcmode_2.setItemText(3, _translate("Form", "待机存储"))
        self.pushButton_dpcmode.setText(_translate("Form", "工作模式更新"))
        self.pushButton_orbit.setText(_translate("Form", "轨道序号更新"))
        self.pushButton_orbit_time.setText(_translate("Form", "轨道周期计算"))
        self.label_32.setText(_translate("Form", "轨道序号/十进制"))
        self.label_33.setText(_translate("Form", "轨道周期/分钟"))
        self.label_34.setText(_translate("Form", "轨道周期/源码"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "分系统注数"))

